const changeVariablesConstant = [
    "REACT_APP_PAGE_DARK_COLOR",
    "REACT_APP_FIRST_BACKGROUND_DARK_COLOR",
    "REACT_APP_SECOND_BACKGROUND_DARK_COLOR",
    "REACT_APP_FIRST_TEXT_DARK_COLOR",
    "REACT_APP_THIRD_TEXT_DARK_COLOR",
    "REACT_APP_FIRST_BORDER_DARK_COLOR",
    "REACT_APP_FIRST_DARK_SHADOW",
    "REACT_APP_SECOND_DARK_SHADOW",
    "REACT_APP_FIRST_MATERIAL_DARK_COLOR",
    "REACT_APP_DISABLE_BG_DARK_COLOR",
    "REACT_APP_DISABLE_TEXT_DARK_COLOR",
]

export default changeVariablesConstant